services:
  app:
    image: tms/FindYourTutor
    build:
      context: .
    container_name: "app"
    depends_on:
      - db
    environment:
      -SPRING_DATASOURSE_URL=jdbc:postgresql://db:5432/tms
    ports:
      - 8080:8080

  db:
    image: postgres:15
    container_name: db
    environment:
      - POSTGRES_DB=tms
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=41241irena!
